version: '3'
services:
    api:
        build:
            context: .
            dockerfile: docker/php-fpm/Dockerfile
        ports:
            - '9000:8000'
        volumes:
            - ./:/var/www/html/api
