version: '3'
services:
    api:
        build:
            context: .
            dockerfile: docker/php-fpm/Dockerfile
        ports:
            - '9000:8000'
        environment:
            - APP_DEBUG=false
            - DB_CONNECTION=pgsql
            - DB_HOST=10.0.0.250
            - DB_PORT=5432
            - DB_DATABASE=LinkDB_Cervantes
            - DB_USERNAME=postgres
            - DB_PASSWORD=cer_2011!
            - JWT_SECRET=y7hwnNtykcssoYUzGeUSTPPPchoBc3uugmenDcUwwEGj5LvkJSkdoeUnEAKosgNL
            - JWT_ALGO=HS256
        volumes:
            - ./:/var/www/html/api
